### ISSUE TITLE
Unhandled exception if database is not consistent  

### ISSUE THREAD

**Issue by TimoMichi** [DivineThreepwood/bcozy#1]
Bcozy doesn't start due to unhandled exception that is thrown in case a corresponding device of a unit is not present in the database. 

```
Exception in Application stop method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openbase.jul.exception.InstantiationException: Could not instantiate BackgroundPane!
	at org.openbase.bco.bcozy.view.BackgroundPane.<init>(BackgroundPane.java:76)
	at org.openbase.bco.bcozy.BCozy.start(BCozy.java:112)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	... 1 more
Caused by: org.openbase.jul.exception.InstantiationException: Could not instantiate LocationPane!
	at org.openbase.bco.bcozy.view.location.LocationPane.<init>(LocationPane.java:138)
	at org.openbase.bco.bcozy.view.location.LocationPane.getInstance(LocationPane.java:167)
	at org.openbase.bco.bcozy.view.BackgroundPane.<init>(BackgroundPane.java:42)
	... 10 more
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.bcozy.view.location.ZonePolygon!
	at org.openbase.bco.bcozy.view.location.AbstractUnitPolygon.init(AbstractUnitPolygon.java:53)
	at org.openbase.bco.bcozy.view.location.LocationPane.<init>(LocationPane.java:94)
	... 12 more
Caused by: org.openbase.jul.exception.NotAvailableException: Context[Unit[ddc5097e-1018-443d-b288-e27e3a247e5d|Home]] is not available!
	at org.openbase.bco.dal.remote.unit.Units.getUnit(Units.java:263)
	at org.openbase.bco.bcozy.view.location.AbstractUnitPolygon.init(AbstractUnitPolygon.java:51)
	... 13 more
Caused by: org.openbase.jul.exception.NotAvailableException: Context[UnitRemote[ddc5097e-1018-443d-b288-e27e3a247e5d]] is not available!
	at org.openbase.bco.dal.remote.unit.Units.getUnitRemote(Units.java:195)
	at org.openbase.bco.dal.remote.unit.Units.getUnit(Units.java:261)
	... 14 more
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.dal.remote.unit.location.LocationRemote!
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableRemote.init(AbstractConfigurableRemote.java:79)
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableRemote.init(AbstractConfigurableRemote.java:46)
	at org.openbase.bco.dal.remote.unit.UnitRemoteFactoryImpl.newInitializedInstance(UnitRemoteFactoryImpl.java:221)
	at org.openbase.bco.dal.remote.unit.Units.getUnitRemote(Units.java:175)
	... 15 more
Caused by: org.openbase.jul.exception.NotAvailableException: Entry[f79b60b8-168c-4bf7-9b1b-87fb0c999224]] is not available! Nearest neighbor is UnitConfig[Inside] or UnitConfig[LeftWindowReedSwitch].
	at org.openbase.jul.storage.registry.AbstractRegistry.get(AbstractRegistry.java:319)
	at org.openbase.jul.storage.registry.RemoteRegistry.getMessage(RemoteRegistry.java:78)
	at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.getUnitConfigById(UnitRegistryRemote.java:229)
	at org.openbase.bco.dal.remote.service.ServiceRemoteManager.applyConfigUpdate(ServiceRemoteManager.java:85)
	at org.openbase.bco.dal.remote.unit.location.LocationRemote.applyConfigUpdate(LocationRemote.java:117)
	at org.openbase.bco.dal.remote.unit.location.LocationRemote.applyConfigUpdate(LocationRemote.java:65)
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableRemote.init(AbstractConfigurableRemote.java:76)
	... 18 more
Exception running application org.openbase.bco.bcozy.BCozy

```

**Comment by DivineThreepwood** [comment]
Issue moved to [openbase/bco.dal #103](https://github.com/openbase/bco.dal/issues/103) via [**ZenHub**](https://www.zenhub.com/)
