### ISSUE TITLE
Random JavaFX Application Thread java.lang.NullPointerException

### ISSUE THREAD

**Issue by DivineThreepwood** [DivineThreepwood/bcozy#10]
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```
This bug is related to (https://bugs.openjdk.java.net/browse/JDK-8180943) where it is incomplete closed because of missing test application. If we find a solution we should report a test case.

**Comment by DivineThreepwood** [comment]
bug occurred again :(

**Comment by DivineThreepwood** [comment]
was fixed by disabling unit panel animation. The animation seems to be broken and should be reimplemented.
