### ISSUE TITLE
BCozy freezes because of a JavaFX Nullpointer looping during heavy animation load.

### ISSUE THREAD

**Issue by DivineThreepwood** [DivineThreepwood/bcozy#62]
<pre>
java.lang.NullPointerException
	at com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
	at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
	at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
	at com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:109)
	at com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:118)
	at com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
	at com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:101)
	at com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:746)
	at com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:131)
	at com.sun.prism.impl.BaseGraphics.<init>(BaseGraphics.java:105)
	at com.sun.prism.impl.ps.BaseShaderGraphics.<init>(BaseShaderGraphics.java:86)
	at com.sun.prism.d3d.D3DGraphics.<init>(D3DGraphics.java:42)
	at com.sun.prism.d3d.D3DGraphics.create(D3DGraphics.java:65)
	at com.sun.prism.d3d.D3DSwapChain.createGraphics(D3DSwapChain.java:131)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
</pre>

This is caused by a javafx bug reported at: https://bugs.openjdk.java.net/browse/JDK-8191183

**Comment by DivineThreepwood** [comment]
Seems to be solved since java 11
