### ISSUE TITLE
NullPointerException in PermissionPaneController

### ISSUE THREAD

**Issue by pLeminoq** [DivineThreepwood/bcozy#64]
Removing a device while bcozy is running causes the following exception in the PermissionPaneController:

<pre>
11:19:02.739 [JavaFX Application Thread] ERROR j.lang.Thread =====================================
11:19:02.739 [JavaFX Application Thread] ERROR o.o.j.s.AbstractExecutorService$1 ═╦═⚀ Fatal implementation error in or by using Thread[JavaFX Application Thread,5,main]: UncaughtException found!
11:19:02.739 [JavaFX Application Thread] ERROR o.o.j.s.AbstractExecutorService$1  ╚════⚀ NullPointerException
11:19:02.739 [JavaFX Application Thread] ERROR o.o.j.s.AbstractExecutorService$1 =====================================
11:19:02.739 [JavaFX Application Thread] ERROR o.o.j.s.AbstractExecutorService$1 Fatal implementation error in or by using Thread[JavaFX Application Thread,5,main]: UncaughtException found!
org.openbase.jul.exception.FatalImplementationErrorException: Fatal implementation error in or by using Thread[JavaFX Application Thread,5,main]: UncaughtException found!
	at org.openbase.jul.schedule.AbstractExecutorService$1.uncaughtException(AbstractExecutorService.java:91)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:363)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:102)
	at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.updateSelectedIndex(TreeTableView.java:3170)
	at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.select(TreeTableView.java:2725)
	at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.clearAndSelect(TreeTableView.java:2655)
	at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.clearAndSelect(TreeTableView.java:2610)
	at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel$4.handle(TreeTableView.java:2521)
	at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel$4.handle(TreeTableView.java:2365)
	at javafx.event.WeakEventHandler.handle(WeakEventHandler.java:79)
	at com.sun.javafx.event.CompositeEventHandler$WeakEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:248)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.TreeItem.fireEvent(TreeItem.java:743)
	at javafx.scene.control.TreeItem.updateChildren(TreeItem.java:920)
	at javafx.scene.control.TreeItem.lambda$new$113(TreeItem.java:412)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:183)
	at com.jfoenix.controls.RecursiveTreeItem.lambda$null$8(RecursiveTreeItem.java:187)
	at com.jfoenix.controls.RecursiveTreeItem$$Lambda$9.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.jfoenix.controls.RecursiveTreeItem.lambda$addChildrenListener$9(RecursiveTreeItem.java:183)
	at com.jfoenix.controls.RecursiveTreeItem$$Lambda$7.onChanged(Unknown Source)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at com.sun.javafx.collections.ObservableListWrapper.clear(ObservableListWrapper.java:157)
	at org.openbase.bco.bcozy.permissions.PermissionsPaneController.fillTable(PermissionsPaneController.java:159)
	at org.openbase.bco.bcozy.permissions.PermissionsPaneController.lambda$fillTable$6(PermissionsPaneController.java:151)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
11:19:02.740 [JavaFX Application Thread] ERROR o.o.j.s.AbstractExecutorService$1 =====================================
</pre>

**Comment by DivineThreepwood** [comment]
bcozy development has been freezed.
